/*
** ###################################################################
**
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**
**     Filename  : OSD_MUTE.C
**
**     Project   : itext_gp32
** 
**     Processor : MC68HC908GP32CFB
**
**     Beantype  : BitIO
**
**     Version   : Bean 02.021, Driver 02.15, CPU db: 2.89.000
**
**     Compiler  : Metrowerks HC08 C Compiler
**
**     Date/Time : 29/12/05, 17:21
**
**     Abstract  :
**
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this bean are mostly implemented as a macros 
**         (if supported by target language and compiler).
**
**     Settings  :
**
**         Used pin                    : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       23            |  PTB1_AD1
**             ----------------------------------------------------
**
**         Port name                   : PTB
**
**         Bit number (in port)        : 1
**         Bit mask of the port        : 2
**
**         Initial direction           : Input (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 1
**         Initial pull option         : off
**
**         Port data register          : PTB       [1]
**         Port control register       : DDRB      [5]
**
**         Optimization for            : speed
**
**     Contents  :
**
**         SetDir - void OSD_MUTE_SetDir(bool Output);
**         GetVal - bool OSD_MUTE_GetVal(void);
**         PutVal - void OSD_MUTE_PutVal(bool Output);
**         ClrVal - void OSD_MUTE_ClrVal(void);
**         SetVal - void OSD_MUTE_SetVal(void);
**
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
**
** ###################################################################
*/

#include "OSD_MUTE.h"

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

/*
** ===================================================================
**     Method      :  OSD_MUTE_GetVal (bean BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---        - Input value (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
/*
bool OSD_MUTE_GetVal(void)

**  This method is implemented as a macro. See OSD_MUTE.h file.  **

*/

/*
** ===================================================================
**     Method      :  OSD_MUTE_PutVal (bean BitIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Value      - Output value (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void OSD_MUTE_PutVal(byte Value)
{
  if (Value) {                         /* Is it one to be written? */
    Shadow_PTB |= 2;                   /* Set bit in shadow variable */
    PTB |= 2;                          /* Set bit on port */
  }
  else {                               /* Is it zero to be written? */
    Shadow_PTB &= ~2;                  /* Clear bit in shadow variable */
    PTB &= ~2;                         /* Clear bit on port */
  }
}

/*
** ===================================================================
**     Method      :  OSD_MUTE_SetVal (bean BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**           a) direction = Input  : sets the output value to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void OSD_MUTE_SetVal(void)

**  This method is implemented as a macro. See OSD_MUTE.h file.  **
*/

/*
** ===================================================================
**     Method      :  OSD_MUTE_ClrVal (bean BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**           a) direction = Input  : sets the output value to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void OSD_MUTE_ClrVal(void)

**  This method is implemented as a macro. See OSD_MUTE.h file.  **
*/

/*
** ===================================================================
**     Method      :  OSD_MUTE_SetDir (bean BitIO)
**
**     Description :
**         This method sets direction of the bean.
**     Parameters  :
**         NAME       - DESCRIPTION
**         DirOutput  - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void OSD_MUTE_SetDir(byte Output)
{
  if (Output) {                        /* Is given direction output? */
    PTB = (PTB & ~2)|(Shadow_PTB & 2); /* Restore correct value of output from shadow variable */
    DDRB |= 2;                         /* Set direction to output */
  }
  else                                 /* Is given direction input? */
    DDRB &= ~2;                        /* Set direction to input */
}

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 03.23 for 
**     the Motorola HC08 series of microcontrollers.
**
** ###################################################################
*/
